name: finger_print
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_button: ^0.2.0
  animated_text_kit: ^4.2.2
  audioplayers: ^5.2.1
  confetti: ^0.7.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.4
  get: ^4.6.6
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/

  fonts:
    - family: uthmanic
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
